substitutions:
  name: clima-monitor-mitsubishi
  friendly_name: ClimaMonitorMitsubishi

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

one_wire:
  - id: "dallas_hub_1"
    platform: gpio
    pin: D1
#  - id: "dallas_hub_2"
#    platform: gpio
#    pin: D3


sensor:
  - platform: pulse_counter
    pin:
      number: 14
      mode:
        input: true
        pullup: true
    unit_of_measurement: 'rpm'
    name: 'fan_rpm'
    id: fan_rpm
    update_interval: 15s
    filters:
     - multiply: 0.08333  #12 pulses per rev

#  - platform: pulse_width
#    pin: D6
#    name: Pulse Width Sensor

  - platform: dallas_temp
    address: 0xde0000006a4xxxxx          #change to your DS1820  address
    one_wire_id: "dallas_hub_1"
    name: temperatureAirIntake
    id: temperatureAirIntake
    update_interval: 15s
  - platform: dallas_temp
    address: 0xdc00000082fxxxxx        #change to your DS1820 address
    one_wire_id: "dallas_hub_1"
    name: temperatureAirOut
    id: temperatureAirOut
    update_interval: 15s    

  - platform: template   
    name: 'airflow_m3h'
    id: airflow_m3h
    unit_of_measurement: 'm3h'
    update_interval: 15s
    lambda: !lambda |-
      return  id(fan_rpm).state / 1.42;        #1.42 works well for SRK/SRC20 

  - platform: homeassistant
    id: mitsubishi_power
    entity_id: sensor.shellymitsubishipower_switch_0_power


  - platform: template   
    name: 'COP_Mitsubishi'
    update_interval: 15s
    lambda: !lambda |-
      return ( id(temperatureAirOut).state - id(temperatureAirIntake).state )* 0.34 * id(airflow_m3h).state / id(mitsubishi_power).state;
    
#      return  id(fan_rpm).state / 1.42;



# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  networks:
    - ssid: "yourwifi1"
      password: !secret wifi_password

    - ssid: "yourwifi2"
      password: !secret wifi_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.


captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:
